### ISSUE TITLE
Best practices TODO

### ISSUE THREAD

**Issue by anandbaburajan** [FOSS-Cell-GECPKD/pixelvibe#4]
### Code
* [ ] Proper readable and maintable code with consistent spacing and indentation
* [ ] Functions follow the "Do One Thing" rule (single-responsibility)
* [ ] Followed DRY (Don’t Repeat Yourself)
* [ ] Added comments wherever required
* [ ] Proper naming conventions
* [ ] Avoided deep nesting

### Readme
* [x] Badges (similar to the Gitter badge. You can maybe use: https://shields.io/)
* [x] Description (why this project exists)
* [x] Features (working of the project)
* [ ] Setup (Quick start instructions with how to download and use your project)
* [x] Contributing (How can others contribute?)
* [x] License ("This project is licensed under the <your license>")

### Tests and CI/CD
* [ ] Wrote tests
* [ ] Deployed the project (if possible)
* [ ] Added CI/CD tools to your project (maybe CircleCI or TravisCI) (if possible)

**Comment by micksharma** [comment]
Can I work on this issue as a GSSOC 2021 participant.

**Comment by Fab-Gaurav** [comment]
@AnandBaburajan  as a participant of GSSOC'21 can I work on this issue.

**Comment by anandbaburajan** [comment]
Hi @Fab-Gaurav and @micksharma! This issue is simply to track the best practices and would be taken care by @ankitapuri (the project admin). @ankitapuri please put the `gssoc21` labels for issues eligible for GSSoC participants. :D

**Comment by ankitapuri** [comment]
> Hi @Fab-Gaurav and @micksharma! This issue is simply to track the best practices and would be taken care by @ankitapuri (the project admin). @ankitapuri please put the `gssoc21` labels for issues eligible for GSSoC participants. :D

Sure , I'll do it .

**Comment by anandbaburajan** [comment]
@ankitapuri the labels need to be exactly `gssoc21` if I understood correctly from their instructions at Discord. Please check.

**Comment by ankitapuri** [comment]
> @ankitapuri the labels need to be exactly `gssoc21` if I understood correctly from their instructions at Discord. Please check.

Made the changes 👍
